"use client";
import { useRef, useState, useTransition } from "react";
import { getCorrectionScreenshot, requestDistanceCorrectionUpload, submitDistanceCorrection } from "@/app/actions/distanceCorrections";
import { errorMessage } from "@/lib/errors";

export function DistanceCorrection({ journeyId, recordedKm, correction }: { journeyId: string; recordedKm: number; correction: { id: string; status: string; submittedDistanceKm: number; finalDistanceKm: number | null } | null }) {
  const [open, setOpen] = useState(false), [step, setStep] = useState(1), [file, setFile] = useState<File | null>(null), [path, setPath] = useState(""), [value, setValue] = useState(""), [error, setError] = useState(""), [pending, start] = useTransition(); const input = useRef<HTMLInputElement>(null);
  if (correction) return <div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-muted"><span>Correction: {["APPROVED", "AUTO_VERIFIED"].includes(correction.status) ? `Verified · ${correction.finalDistanceKm} km` : correction.status === "REJECTED" ? "Not approved" : "Pending verification"}</span><button className="min-h-9 rounded px-2 text-sm text-brand underline" onClick={async () => { try { window.open(await getCorrectionScreenshot(correction.id), "_blank", "noopener,noreferrer"); } catch (e) { setError(errorMessage(e)); } }}>View screenshot</button>{error && <span className="text-red-600">{error}</span>}</div>;
  async function upload() { if (!file) return setError("Choose a screenshot first."); try { const ticket = await requestDistanceCorrectionUpload({ journeyId, filename: file.name, mimeType: file.type, size: file.size }); const r = await fetch(ticket.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!r.ok) throw new Error("Couldn’t upload right now. Please check your connection and try again."); setPath(ticket.path); setStep(2); } catch (e) { setError(errorMessage(e)); } }
  function submit() { const n = Number(value); if (!path || !file || !Number.isFinite(n)) return setError("Enter a valid distance."); start(async () => { try { await submitDistanceCorrection({ journeyId, submittedDistanceKm: n, screenshot: { path, name: file.name, type: file.type as "image/jpeg", size: file.size } }); setStep(4); } catch (e) { setError(errorMessage(e)); } }); }
  return <div className="mt-1 text-xs">{!open ? <><span className="text-muted">Distance looks wrong?</span> <button className="text-brand underline" onClick={() => setOpen(true)}>Correct Distance</button></> : <div className="mt-2 w-full max-w-md rounded border bg-bg p-3 text-sm" role="dialog" aria-modal="true" aria-label="Correct Trip Distance">{step === 1 && <><b>Correct Trip Distance</b><p className="mt-1 text-muted">Upload a Google Maps screenshot showing the route and distance.</p><input ref={input} className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={e => setFile(e.target.files?.[0] ?? null)} /><button className="btn-ghost mt-2 w-full justify-center" onClick={() => input.current?.click()}>Upload Screenshot</button>{file && <button className="btn-primary mt-2 w-full justify-center" onClick={upload}>Continue</button>}</>}{step === 2 && <><label className="block font-medium" htmlFor={`correction-${journeyId}`}>How much distance does Google Maps show?</label><input id={`correction-${journeyId}`} className="input mt-2 w-full" inputMode="decimal" type="number" min="0.01" step="0.01" placeholder="18.6" value={value} onChange={e => setValue(e.target.value)} /><button className="btn-primary mt-2 w-full justify-center" onClick={() => setStep(3)}>Continue</button></>}{step === 3 && <><b>Review correction</b><p className="mt-2">Recorded: {recordedKm.toFixed(2)} km<br/>Submitted: {value} km</p><button className="btn-primary mt-2 w-full justify-center" disabled={pending} onClick={submit}>{pending ? "Submitting…" : "Submit Correction"}</button></>}{step === 4 && <><b>Correction submitted</b><p className="mt-1 text-muted">Your admin will review the screenshot and update the distance.</p></>}{error && <p className="mt-2 text-red-600" role="alert">{error}</p>}<button className="mt-3 text-muted underline" onClick={() => setOpen(false)}>Cancel</button></div>}</div>;
}
