"use client";
import { useRef, useState, useTransition } from "react";
import { CheckCircle2, MapPinned, PencilLine, Upload } from "lucide-react";
import { getCorrectionScreenshot, requestDistanceCorrectionUpload, submitDistanceCorrection } from "@/app/actions/distanceCorrections";
import { errorMessage } from "@/lib/errors";
import { t, DEFAULT_LANG, type Lang } from "@/lib/i18n";

type Correction = { id: string; status: string; submittedDistanceKm: number; finalDistanceKm: number | null } | null;

export function DistanceCorrection({ journeyId, recordedKm, correction, lang = DEFAULT_LANG }: { journeyId: string; recordedKm: number; correction: Correction; lang?: Lang }) {
  const [open, setOpen] = useState(false), [step, setStep] = useState(1), [file, setFile] = useState<File | null>(null), [path, setPath] = useState(""), [value, setValue] = useState(""), [error, setError] = useState(""), [pending, start] = useTransition(); const input = useRef<HTMLInputElement>(null);
  if (correction) {
    const status = ["APPROVED", "AUTO_VERIFIED"].includes(correction.status)
      ? `${t(lang, "correctionVerified")} · ${correction.finalDistanceKm} km`
      : correction.status === "REJECTED" ? t(lang, "correctionNotApproved") : t(lang, "correctionPending");
    return <div className="mt-2 flex flex-wrap items-center gap-2 text-xs"><span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/10 px-2 py-1 font-medium text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5" />{status}</span><button className="min-h-9 rounded px-2 text-sm text-brand underline" onClick={async () => { try { window.open(await getCorrectionScreenshot(correction.id), "_blank", "noopener,noreferrer"); } catch (e) { setError(errorMessage(e)); } }}>{t(lang, "viewScreenshot")}</button>{error && <span className="text-red-600">{error}</span>}</div>;
  }
  async function upload() { if (!file) return setError(t(lang, "chooseScreenshotFirst")); try { const ticket = await requestDistanceCorrectionUpload({ journeyId, filename: file.name, mimeType: file.type, size: file.size }); const r = await fetch(ticket.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!r.ok) throw new Error("Couldn’t upload right now. Please check your connection and try again."); setPath(ticket.path); setStep(2); } catch (e) { setError(errorMessage(e)); } }
  function submit() { const n = Number(value); if (!path || !file || !Number.isFinite(n)) return setError(t(lang, "enterDistanceValid")); start(async () => { try { await submitDistanceCorrection({ journeyId, submittedDistanceKm: n, screenshot: { path, name: file.name, type: file.type as "image/jpeg", size: file.size } }); setStep(4); } catch (e) { setError(errorMessage(e)); } }); }
  return <div className="mt-2"><button type="button" className="flex w-full items-center justify-between gap-3 rounded-lg border border-brand/30 bg-brand/5 px-3 py-2 text-left transition hover:border-brand hover:bg-brand/10 focus:outline-none focus:ring-2 focus:ring-brand/40" onClick={() => setOpen(true)}><span className="flex min-w-0 items-center gap-2"><span className="rounded-full bg-brand p-1.5 text-white"><PencilLine className="h-3.5 w-3.5" /></span><span><span className="block text-sm font-semibold text-brand">{t(lang, "correctDistance")}</span><span className="block text-xs text-muted">{t(lang, "correctDistanceHint")}</span></span></span><span className="shrink-0 text-xs font-medium text-brand">{lang === "hi" ? "सुधारें →" : "Fix it →"}</span></button>{open && <div className="mt-2 w-full max-w-md rounded-lg border border-brand/20 bg-bg p-3 text-sm shadow-sm" role="dialog" aria-modal="true" aria-label={t(lang, "correctTripDistance")}>{step === 1 && <><div className="flex items-center gap-2 font-semibold"><MapPinned className="h-4 w-4 text-brand" />{t(lang, "correctTripDistance")}</div><p className="mt-1 text-muted">{t(lang, "uploadScreenshotHint")}</p><input ref={input} className="hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={e => setFile(e.target.files?.[0] ?? null)} /><button className="btn-ghost mt-3" onClick={() => input.current?.click()}><Upload className="h-4 w-4" />{t(lang, "uploadMapScreenshot")}</button>{file && <button className="btn-primary mt-2" onClick={upload}>Continue</button>}</>}{step === 2 && <><label className="block font-medium" htmlFor={`correction-${journeyId}`}>{t(lang, "howMuchGoogleMaps")}</label><input id={`correction-${journeyId}`} className="input mt-2 w-full" inputMode="decimal" type="number" min="0.01" step="0.01" placeholder="18.6 km" value={value} onChange={e => setValue(e.target.value)} /><button className="btn-primary mt-2" onClick={() => setStep(3)}>Continue</button></>}{step === 3 && <><b>{t(lang, "reviewCorrection")}</b><p className="mt-2">{t(lang, "recordedDistance")}: {recordedKm.toFixed(2)} km<br/>{t(lang, "submittedDistance")}: {value} km</p><button className="btn-primary mt-2" disabled={pending} onClick={submit}>{pending ? t(lang, "submittingCorrection") : t(lang, "submitCorrection")}</button></>}{step === 4 && <><div className="flex items-center gap-2 font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4" />{t(lang, "correctionSubmitted")}</div><p className="mt-1 text-muted">{t(lang, "correctionSubmittedHelp")}</p></>}{error && <p className="mt-2 text-red-600" role="alert">{error}</p>}<button className="mt-3 text-muted underline" onClick={() => setOpen(false)}>{t(lang, "cancel")}</button></div>}</div>;
}
